runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: 'Ubuntu package'
    - name: Install pre-built package
      shell: bash
      run: apt-get -y install ./nvc_*.deb
    - name: Check --version output
      shell: bash
      run: nvc --version
