name: Build Docker image

on:
  workflow_dispatch:

jobs:
  docker:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Login to ghcr.io
        run : |
          echo "${{ secrets.GHCR_TOKEN }}" | \
            docker login -u ${{ vars.GHCR_USER }} --password-stdin ghcr.io
      - name: Build Docker image
        run: ./test/docker/build.sh
