name: Test OSVVM on Windows

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * 0'

jobs:
  test-osvvm:
    name: Test OSVVM
    runs-on: windows-2022
    steps:
      - uses: nickg/setup-nvc@v1
        with:
          version: latest
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/checkout@v4
        with:
          repository: OSVVM/OsvvmLibraries
          path: OsvvmLibraries
          ref: dev
          submodules: recursive
          fetch-depth: 1
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            mingw-w64-x86_64-tcllib
      # - name: Test OSVVM
      #   shell: powershell
      #   run: |
      #     $Env:OSVVM_DIR = $(Resolve-Path -Path OsvvmLibraries)
      #     echo $Env:OSVVM_DIR
      #     $Env:OSVVM_MUST_BUILD = 1
      #     Get-ChildItem -Path $Env:OSVVM_DIR -Recurse -Filter "VendorScripts_NVC.tcl" | ForEach-Object {
      #       (Get-Content $_.FullName) -replace 'puts \$SimulateMessage', '' | Set-Content $_.FullName
      #     }
      #     nvc.exe --do .\test\test-osvvm.tcl
      - name: Test OSVVM
        shell: msys2 {0}
        run: |
          export PATH=/c/Program\ Files/NVC/bin:$PATH
          export OSVVM_DIR=$(realpath OsvvmLibraries)
          export OSVVM_MUST_BUILD=1
          find $OSVVM_DIR -name VendorScripts_NVC.tcl -exec \
            sed -i '/puts $SimulateMessage/d' \{} \;
          tclsh ./test/test-osvvm.tcl
      - name: Publish results
        uses: dorny/test-reporter@v1
        with:
          name: OSVVM Regression Results
          path: ./*.xml
          reporter: java-junit
          list-suites: all
          list-tests: failed
          fail-on-error: true
          fail-on-empty: true
      - name: Upload logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: osvvm-logs
          path: |
            *.log
            *.yml
            *.html
            *.xml
            reports/*.html
            reports/**/*.html
            logs/**/*.*
            reports/*.css
            reports/osvvm.png
          if-no-files-found: error
